CHANGELOG.md
src/vault/client/http.clj
src/vault/env.clj

This changes the default behavior of the HTTP client so it no longer tries to revoke all outstanding secrets on component stop. This can be controlled with a new option, if desired.

Revoke on stop option

---

src/vault/client/http.clj

Fixes #10
```clojure
=> (require '[vault.core :as vault] 'vault.client.http)
=> (def client (vault/new-client "https://localhost:8200"))
=> (vault/status client)
; SunCertPathBuilderException: unable to find valid certification path to requested target
; sun.security.provider.certpath.SunCertPathBuilder.build (SunCertPathBuilder.java:141)
=> (alter-var-root #'client assoc :http-opts {:insecure? true})
=> (vault/status client)
{:cluster-id "1e40d6e6-d202-7aff-5d1c-ae061b991310",
:cluster-name "vault-cluster-b031f813",
:initialized true,
:sealed false,
:server-time-utc 1498863935,
:standby false,
:version "0.6.4"}
```

HTTP client request opts

---

src/vault/client/http.clj
src/vault/client/mock.clj
src/vault/core.clj

Add support for a `:not-found` option in `read-secret` and clarify the contract. If `:not-found` is not set and a secret is missing, both clients throw an exception now, otherwise they will return the supplied value.
Fixes #7

Secret not found support

---

src/vault/client/http.clj
src/vault/core.clj

Add LDAP auth support.
Tested here, appears to work.

Add LDAP support #14

---

project.clj
src/vault/client/http.clj
src/vault/core.clj
src/vault/env.clj

Adding top-level support to using a wrapping token to authenticate with vault. This is useful in the case of single-run jobs being passed a credential to do worth without requiring secrets in the job's environment or configuration.
Incidentally fixed `unwrap!` to use the passed-in token as `X-Vault-Token` which currently fails for an unauthenticated client.
Also while I'm at it adding app-role config-client support.

Add wrap token config support

---

src/vault/client/http.clj
src/vault/core.clj

This fixes the log/vault spam issue with periodic tokens and app-role services.

Renewing the client token should update the internal auth state

---

src/vault/client/http.clj

In support of adding a small extension to vault-clj, open up authenticate! dispatching.
Eg, an external library could implement `vault.client.http.authenticate-type!` for aws instance auth with:
```clojure
(:require '[big-annoying-aws-library :as aws])
(defmethod vault.client.http.authenticate-type! :aws-iam
[client _ credentials]
(let [{:keys [iam-role] credentials]
(aws/do-instance-authentication-hoop-jumping iam-role))
```

move authenticate dispatch to multimethod for external dispatch

---

CHANGELOG.md
project.clj
src/vault/client/http.clj

This is mostly aimed at upgrading `clj-http` to the 3.X series to unblock usage with Riemann 0.3.X, but also includes a couple other dependency upgrades. I've also removed the dependency on `digest` by doing the (small) amount of Java interop necessary to calculate a SHA-256 hash directly.

Upgrade dependencies

---

CHANGELOG.md
src/vault/client/api_util.clj
src/vault/client/http.clj
src/vault/client/mock.clj
src/vault/secrets/kvv2.clj
test/vault/client/http_test.clj
test/vault/secrets/kvv2_test.clj
test/vault/secrets/secret-fixture-kvv2.edn

Related to #39 
Exposes read, create/update, and delete API endpoints for KV V2 metadata (which holds info about all the secret versioning and secret specific configurations).
Also introduces a macro to help deal with repetition in API error handling for secret engine read functions.

KV-V2 Metadata CRUD

---

src/vault/client/mock.clj
src/vault/secrets/kvv2.clj
test/vault/secrets/kvv2_test.clj

Resolves #39 by exposing the kv-v2 list secrets endpoint. Works with mocking too.
I left a TODO in the mock client, but I think this is ready for review anyway. The issue can be addressed later in a minor version release

KV-V2 List Secrets

---

src/vault/lease.clj
test/vault/client/http_test.clj
test/vault/lease_test.clj
test/vault/secrets/kvv1_test.clj

This helps mitigate secret expiration (outside the control
of the client such as in a network outage) that would otherwise
be rotatable. before this change, a lease wasn't marked
'renewable false' during the run of manage-leases so it
would just be swept. instead, this at least attempts to
rotate first before sweeping it for being expired.

consider expired, rotatable leases rotatable

---

.gitignore
src/vault/authenticate.clj
src/vault/client/http.clj
src/vault/core.clj
test/vault/client/http_test.clj

To sanity check on this vault does expect the iam payload values to be b64 encoded, at the moment I have left that to the consumer to understand as I didn't want to pull additional dependencies into the project. Let me know if you think that is worth changing.

Support aws IAM authentication

---

src/vault/authenticate.clj

This was mistakenly using `log/info` and logging a raw format string.

Use `log/infof` for log message in vault.authenticate namespace

---

.gitignore
bb.edn
deps.edn
dev/user.clj
project.clj
src/vault/authenticate.clj
src/vault/client/api_util.clj
src/vault/client/http.clj
src/vault/client/mock.clj
src/vault/env.clj
src/vault/lease.clj
src/vault/timer.clj
test/vault/client/http_test.clj
test/vault/secrets/kvv1_test.clj
test/vault/secrets/kvv2_test.clj

This is a rough PR - mainly to visualize the amount of changes. 
* I migrated from clj-http to httpkit (API is mostly compatible) - minimal changes
* Added deps.edn for easier consumption of library via git url or local url
* Added bb.edn with sample script to test secret extraction from vault
* Changed clean-body function to make it work with vault 1.7.x API
* Replaced commons hex with clojure equivalent
Fixes #53 
Ideas for improvement:
* Add integration tests using https://www.testcontainers.org/  - start vault in a container and run API tests against it

#53 support babashka use httpkit + api updates fro vault 1.7.1 + deps.edn

---

project.clj

lein-cloverage 1.2.1 -> 1.2.2
clojure 1.10.1 -> 1.10.3
org.clojure/tools.logging 1.1.0 -> 1.2.3
amperity/envoy 0.3.3 -> 1.0.0
ch.qos.logback/logback-classic 1.2.5 -> 1.2.10
org.clojure/tools.namespace 1.1.0 -> 1.2.0

Update dependencies to latest versions

---

src/vault/client/http.clj
src/vault/client/mock.clj
src/vault/core.clj

Add support for the `/auth/token/create-orphan` endpoint, so that we can securely give services permissions to create orphan tokens without `sudo` on the main `/auth/token/create` endpoint.

Add create-orphan-token! method

---

src/vault/authenticate.clj
src/vault/client/http.clj
test/vault/client/http_test.clj

After upgrading to 1.1.0 to add support for the orphan token endpoint, we discovered that services were failing to authenticate with app-role with the new version of the library. This upgrade crossed the http-kit switchover, so I suspected that to be the cause. We were seeing errors like the following:
```
Vault API server errors: failed to parse JSON input: invalid character 'r' looking for beginning of value
{:type :vault.client.api-util/api-error,
:status 400,
:errors "failed to parse JSON input: invalid character 'r' looking for beginning of value"}
```
This is suspicious because one of the posted fields is `role_id`, which also begins with the letter "r". After a little investigation, I found that `http-kit` _always_ turns `:form-params` [into a query-string style …

Switch :form-params to :body for http-kit conversion

---

.circleci/config.yml

clj-kondo also lives in the [clj-kondo](https://github.com/clj-kondo) organization now, not under [borkdude](https://github.com/borkdude)'s account. This should resolve the linting failures due to unrecognized functions from Clojure v1.11 (see those failures [here](https://github.com/amperity/vault-clj/pull/87#issuecomment-1264250542)).

Bump clj-kondo to latest version.

---

dev/vault/repl.clj
src/vault/auth/token.clj
src/vault/auth/userpass.clj
src/vault/util.clj
test/vault/auth/userpass_test.clj

Implemented the [Userpass](https://www.vaultproject.io/api-docs/auth/userpass)'s `login` method. Validated with the added integration test for userpass.
This should resolve https://github.com/amperity/vault-clj/issues/78.

Add Userpass auth method

---

src/vault/auth/github.clj
test/vault/auth/github_test.clj

Implemented the [GitHub](https://www.vaultproject.io/api-docs/auth/github) auth's [login](https://www.vaultproject.io/api-docs/auth/github#login) method. This should resolve https://github.com/amperity/vault-clj/issues/79.
Validated with a local vault server and my personal Github token, using the Amperity organization. I figured it probably didn't  make sense to have an integration test for this, but I'm open to ideas for how to durably test this.
Validation steps:
- In the terminal:
```shell
❯ vault auth enable -path=test-mount github
Success! Enabled github auth method at: test-mount/
❯ vault write auth/test-mount/config organization=amperity
Success! Data written to: auth/test-mount/config
❯ vault write auth/test-mount/map/teams/developers value=default
Success! Data written to: …
```

Add GitHub auth method.

---

src/vault/auth/kubernetes.clj
test/vault/auth/kubernetes_test.clj

Implemented the [Kubernetes](https://www.vaultproject.io/api-docs/auth/kubernetes) auth's [login](https://www.vaultproject.io/api-docs/auth/kubernetes#login) method. This should resolve https://github.com/amperity/vault-clj/issues/81.
Similar to https://github.com/amperity/vault-clj/pull/89, I'm not sure it makes sense to write an integration test for this just yet due to the amount of setup it requires, but it's not impossible either. I did run a K8s cluster locally, configured to use my local Vault server and was able to validate the login method using a JWT from a local K8s service account.
Steps to validate:
1. Follow all the steps in https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault
- Instead of starting a vault server how they suggest, I modified `dev/server` to …

Add Kubernetes auth method

---

dev/vault/repl.clj
src/vault/auth/approle.clj
test/vault/auth/approle_test.clj

This should add in support for the [AppRole](https://www.vaultproject.io/api-docs/auth/approle#login-with-approle) `login` function.
I based a majority of the changes off of stuff I saw in the other auth implementations.
With this, Issue #75  should be done. Once this has a ✅ I will go ahead and tackle one of the more complicated issues.

add approle login functionality

---

CHANGELOG.md
src/vault/client/http.clj

As I was building out a control flow handler in our main codebase, I realized that the automatic retries in the HTTP client code are problematic for a few reasons:
1. Clients can't configure the behavior or wait time because it's hard-coded.
2. Using `Thread/sleep` directly will block `http-kit`'s callback thread and doesn't mix well with an async flow model.
3. The control flow can't see these, so it can't annotate an observability span with the failure info.
I concluded that the best thing to do here is to remove the automatic retries and leave it to the control flow to handle.

Remove automatic 5xx retries in the HTTP client

---

CHANGELOG.md
src/vault/auth/approle.clj
src/vault/auth/github.clj
src/vault/auth/kubernetes.clj
src/vault/auth/ldap.clj
src/vault/auth/userpass.clj
src/vault/client/http.clj
src/vault/secret/aws.clj
src/vault/secret/database.clj
src/vault/secret/kv/v1.clj
src/vault/secret/kv/v2.clj
src/vault/secret/transit.clj
src/vault/sys/auth.clj
src/vault/sys/leases.clj
src/vault/sys/mounts.clj

Further changes in response to building out a new control-flow handler - this time focused on how the request metadata is supplied to the flow handler as well as how it's attached to responses.
The `flow/call` method already accepted an `info` argument, but there was no way for each implementation to feed data into that through the HTTP client. Now the `http/call-api` function accepts `:info` as part of the request parameters, which is threaded through the whole call chain. The client also does more work to ensure that gets included in response metadata or exception data, so that the API implementations don't need to worry about that.
I tested this by building out a really simple flow handler which logs/prints the captured metadata, then called some `kv2` operations:
```clojure …
```

Client observability info threading

---

.circleci/config.yml
CHANGELOG.md
dev/vault/repl.clj
doc/cljdoc.edn
src/vault/secret/transit.clj
src/vault/util.clj
test/vault/secret/transit_test.clj
test/vault/util_test.clj

This PR focuses on the [Transit secrets engine](https://developer.hashicorp.com/vault/api-docs/secret/transit) implementation. There are a few bug fixes (several methods did not properly coerce their responses) and two significant behavioral changes.
First, all inputs that need to be sent as a base64 string are automatically encoded by the client, rather than requiring the caller to do so. Similarly, when decrypting data the result is automatically decoded from base64 into a byte array, or the caller can now also opt into string-coercion.
Second, the encryption and decryption batch modes are directly invoked by providing a collection of data rather than a single item, which is much more natural than passing a `nil` for the data and then specifying a separate `:batch-input` option. The …

Transit engine polish

---

CHANGELOG.md
doc/control-flow.md
src/vault/client/flow.cljc
src/vault/client/http.clj
src/vault/client/mock.clj
test/vault/client/flow_test.clj
test/vault/client/http_test.clj

Further developments from pursuing deeper integration in the Amperity app. The "response info" which pulls observability data such as the HTTP status code, headers, request id, and so on is attached to the returned values as metadata, or to exceptions in the `ex-data` map. The control flow handler is expected to pull it from these sources to record to the tracing system.
However, there's one spot where this falls through, because in the event of a non-success response, the `handle-failure` function is called on the exception _before_ it is passed to the control flow, and is allowed to replace it with a value. One use for this is implementing a `:not-found` option, such as in `kv2/read-secret`. An extremely common pattern for this is to tolerate missing secrets by passing `:not-found nil`, …

Pass observability information explicitly to control-flow handler

---

CHANGELOG.md
src/vault/auth.clj
src/vault/client.cljc
src/vault/client/http.clj
src/vault/client/mock.clj
src/vault/lease.cljc
src/vault/secret/kv/v1.clj
src/vault/secret/kv/v2.clj
src/vault/sys/leases.clj
src/vault/util.cljc
test/vault/lease_test.clj
test/vault/secret/kv/v1_test.clj

Despite the HTTP client defining a custom `Object#toString()` and `print-method`, there are cases where the internal state can still be exposed in logs and other print output. This specifically happens when the client is fed into a pretty-printer (such as [clj-commons/pretty](https://github.com/clj-commons/pretty)) which wind up traversing the client's attributes as a record type. This is undesirable, because the `auth` and `leases` fields contain secret information which should remain private.
To address this, we can define a new `Veil` type which hides the data in an internal field. There's a bunch of refactoring to go with this, mostly adjusting callsites to unveil the data before using it. To simplify this, and provide a more consistent interface, several functions in the `vault.auth` …

Veil secrets

---

CHANGELOG.md
build.clj
src/vault/client/http.clj

If you have multiple Vault clusters, for example dev and prod, the Vault address can be useful for debugging and monitoring/observability.
I've tried to update the changelog, and bumped to the next minor version because though very minor, this is technically adding functionality.

Include the `:vault.client/address` in flow handler info
